<<<<<<< HEAD
baseURL: 'http://https://mathewbelcher.netlify.app'
=======
baseURL: http://example.org/
>>>>>>> 83371f9ca51c6828e74031c618432a5149e993e4
languageCode: en-us
title: My New Hugo Site

markup:
  goldmark:
    renderer:
      unsafe: true
